### ISSUE TITLE
increase versionCode/versionName

### ISSUE THREAD

**Issue by IzzySoft** [tastelessjolt/youtube-dl-android#12]
The latest release (v0.12) still shows versionCode 1 and versionName 1.0 – which makes it hard to update (as Android considers it to be the same version as all before). Would you consider increasing it with each release? It must just be higher. So it would eg. be fine to use versionCode:12 and versionName:0.12 or simply increase versionCode by 1 with each new release, and put the real version number into versionName.

**Comment by tastelessjolt** [comment]
I didn't know this. Will do for the next release.

**Comment by IzzySoft** [comment]
Please let me know when it's out (e.g. by closing this issue after the release is available). Thanks!

**Comment by IzzySoft** [comment]
Thanks!
