### ISSUE TITLE
Complete doesn't work

### ISSUE THREAD

**Issue by androidacy-user** [tastelessjolt/youtube-dl-android#14]
Every time I open the app, it just opens Google. When I share a video from YT in Firefox it does the same thing 

_Sent from my TETRA using [FastHub-Libre](https://github.com/thermatk/FastHub-Libre/)_

**Comment by tastelessjolt** [comment]
I don't understand what you mean by "opens Google". Do you mind elaborating? Can you open the app directly and type in/paste the youtube link? And which android version are you using?

**Comment by androidacy-user** [comment]
I'm using Android 8.1. I mean upon launching the app, it immediately opens Google.com in Firefox, and never let's me see the ui
________________________________

**Comment by tastelessjolt** [comment]
That's not how it should work. Can you reinstall the app? And also use the latest version of the app from the releases.

**Comment by androidacy-user** [comment]
Done, didn't help and I had the latest version from F-Droid

**Comment by tastelessjolt** [comment]
I just noticed it when I tried it on a Samsung device. I'll look into it. As for a workaround for now, once it open browser, press back, it takes you to the actual app. And also I didn't upload it on F-Droid though. Can you provide me the link to this app on F-Droid?

**Comment by Silverstar** [comment]
It is on the IzzyOnDroid repository for f-droid:
https://apt.izzysoft.de/fdroid/index/apk/me.harshithgoka.youtubedl

It's a self-made repo for apps which are not on f-droid and the one who provides it finds useful:
https://apt.izzysoft.de/fdroid/index/info

And I just checked, both versions (0.13), from the repo as well as from this release page, request to open a browser and open Google.

Looks like you added that on commit  e38a3b1 in MainActivity.java (don't know how to link to that properly, sorry).

**Comment by tastelessjolt** [comment]
Oh, sorry, I was trying to use the JS interpreter of the webview to speed up the signature decryption, but I forgot to remove the code corresponding. But that should've opened a hidden webview, but on some phones, it doesn't work I guess. Anyway, I'm removing that part and making a new release in the next 20 mins.

**Comment by tastelessjolt** [comment]
Hopefully, `0.14` should fix this. I'm closing this issue now. If you're still facing this issue, feel free to reopen. And also, I didn't test this release on a phone which does open the browser since I didn't have it.  If it's working, please leave a reply here that it's working.

**Comment by androidacy-user** [comment]
For now, it works.
However, downloading doesn't go anywhere. The file will show in my downloads app as queued, and never go anywhere on a 1GbPS internet connection. It never even starts
________________________________

**Comment by tastelessjolt** [comment]
That might be problem with the Downloads app on your phone since I just handoff the download link and where to download to the Android Framework and it takes care of download, pause, retry and notification management. 
I may add an option where the app provides you with the download link which you can paste into any download manager or a browser to download.

**Comment by androidacy-user** [comment]
Probably. Everything except browsers seem to have issues downloading
________________________________
