### ISSUE TITLE
Can't Dismiss The Clipboard

### ISSUE THREAD

**Issue by ledux6** [tastelessjolt/youtube-dl-android#20]
So, I'm trying out to figure out the core methods and how to use them. 

What I did is tried hardcoding the link like this:
```
    public void startPoint(View button) {
        //String url = urlEdit.getText().toString();
        String url = "https://www.youtube.com/watch?v=CQceqbA7kFI";
        startDownload(url);
    }
```
I added a different button that points to this method, but when I try to use it I get the error:
IllegalStateException: No successful match so far
Error connecting to the Internet

**Comment by tastelessjolt** [comment]
So, the error is not because it is using clipboard data, but because there's a change in the scraping of the js function to run to get the signature decrypted. I am not able fix because I broke my gradle and I should reinstall Android Studio.

**Comment by tastelessjolt** [comment]
You can try this now, it should work since I've updated with the new JS function regex from `youtube-dl`. 
I'm closing this now. You can open when you get another error.
