### ISSUE TITLE
Support for API 15 and higher

### ISSUE THREAD

**Issue by nihatalim** [tastelessjolt/youtube-dl-android#3]
Hello. I following this project and this is magnificent approach for discarding server side. And this is my commit for supporting API 19 and higher. 
[LINK HERE](https://github.com/nihatalim/youtube-dl-android/commit/e6557d8621d14de38b16a0d90d83e68adb8ee84f)

Can you help me for supporting API 15 and higher? I think you just need to use GSON instead of org.json.JSONObject. Actually i can't any way to remove element of jsonobject because this api doesn't support actually. This app is not support for API 15 because of only one command line. You can see here.

[LINK HERE](https://github.com/tastelessjolt/youtube-dl-android/blob/56b4a4a7cd08398d84db4a6c9e2351d6f36b319c/app/src/main/java/me/harshithgoka/youtubedl/JSInterpreter.java#L411)

**Comment by tastelessjolt** [comment]
Sorry for replying so late. I'll review your commit and let you know. Btw, using a [multi-threaded downloader](https://github.com/lingochamp/FileDownloader) is a good thing. I was planning on doing that. 

Also, about making it backward compatible, I don't think it is worth to go back until API 15, [API 19]((https://developer.android.com/reference/org/json/JSONArray.html#remove(int))) is good enough. 
If you still want to change to GSON, you can try to replace all JSONObject/JSONArray objects and methods with GSON's corresponding methods. If it works and good enough, then put a PR and I'll merge. :+1:

**Comment by nihatalim** [comment]
When I got free time I gonna try implement Gson, btw did you think create this project as a library? This will very usable to other project as dependency.

**Comment by tastelessjolt** [comment]
I included your changed to support for API 19. As a library, we can but I don't have that much time to completely maintain the library. I would encourage if anyone takes it up. :)
