### ISSUE TITLE
LICENSE.md

### ISSUE THREAD

**Issue by Immortalin** [tastelessjolt/youtube-dl-android#7]

**Comment by tastelessjolt** [comment]
Can you help me, include a `LICENSE.md` as it is my first good code base? I would really appreciate it. 
Or at least suggestions as to which licenses can I use for this project to be on the legal side?

Thank you

**Comment by IzzySoft** [comment]
I'd suggest chosing an aproved FOSS license (see e.g. [here](https://spdx.org/licenses/)) – as that would make your app liable for F-Droid :wink:

Let me know when you've chosen – and if you wish, I can help you getting your app listed at F-Droid then.

**Comment by IzzySoft** [comment]
@Immortalin I don't think closing this before it's solved is a good idea. The project still has no license.

@tastelessjolt would you like to open a new issue instead?

**Comment by tastelessjolt** [comment]
I added a GPL-3.0 licence to the project. So, this issue remains closed.

**Comment by IzzySoft** [comment]
Thanks!
